development:
  auth0_domain: dev-flkogsdb.us.auth0.com
  auth0_client_id: 7w8uMvDWlQ5Y4cPIBgQjeKo4CEeTWL7S
  auth0_client_secret: 6Nsw2krriMZ1bFunyqVf_cTt_cCNhZzSYJktdJE1NSd_gL5bA0wC1fjz2bTfieP-
production:
  auth0_domain: <%= ENV.fetch("AUTH0_DOMAIN") { "" } %>
  auth0_client_id: <%= ENV.fetch("AUTH0_CLIENT_ID") { "" } %>
  auth0_client_secret: <%= ENV.fetch("AUTH0_CLIENT_SECRET") { "" } %>
