// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: netconn.proto

package netconnpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action_ActionType int32

const (
	Action_AUTHENTICATE Action_ActionType = 0
	Action_UPDATEOBJECT Action_ActionType = 1
	Action_REMOVEOBJECT Action_ActionType = 2
	Action_ADDDAMAGE    Action_ActionType = 4
	Action_ADDEFFECT    Action_ActionType = 5
	Action_SENDSIGNAL   Action_ActionType = 6
	Action_ADDSOUND     Action_ActionType = 7
)

// Enum value maps for Action_ActionType.
var (
	Action_ActionType_name = map[int32]string{
		0: "AUTHENTICATE",
		1: "UPDATEOBJECT",
		2: "REMOVEOBJECT",
		4: "ADDDAMAGE",
		5: "ADDEFFECT",
		6: "SENDSIGNAL",
		7: "ADDSOUND",
	}
	Action_ActionType_value = map[string]int32{
		"AUTHENTICATE": 0,
		"UPDATEOBJECT": 1,
		"REMOVEOBJECT": 2,
		"ADDDAMAGE":    4,
		"ADDEFFECT":    5,
		"SENDSIGNAL":   6,
		"ADDSOUND":     7,
	}
)

func (x Action_ActionType) Enum() *Action_ActionType {
	p := new(Action_ActionType)
	*p = x
	return p
}

func (x Action_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_netconn_proto_enumTypes[0].Descriptor()
}

func (Action_ActionType) Type() protoreflect.EnumType {
	return &file_netconn_proto_enumTypes[0]
}

func (x Action_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_ActionType.Descriptor instead.
func (Action_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_netconn_proto_rawDescGZIP(), []int{0, 0}
}

type Action_SignalType int32

const (
	Action_CHIPSEND     Action_SignalType = 0
	Action_GOCHIPSELECT Action_SignalType = 1
	Action_PLAYERDEAD   Action_SignalType = 2
)

// Enum value maps for Action_SignalType.
var (
	Action_SignalType_name = map[int32]string{
		0: "CHIPSEND",
		1: "GOCHIPSELECT",
		2: "PLAYERDEAD",
	}
	Action_SignalType_value = map[string]int32{
		"CHIPSEND":     0,
		"GOCHIPSELECT": 1,
		"PLAYERDEAD":   2,
	}
)

func (x Action_SignalType) Enum() *Action_SignalType {
	p := new(Action_SignalType)
	*p = x
	return p
}

func (x Action_SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_netconn_proto_enumTypes[1].Descriptor()
}

func (Action_SignalType) Type() protoreflect.EnumType {
	return &file_netconn_proto_enumTypes[1]
}

func (x Action_SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_SignalType.Descriptor instead.
func (Action_SignalType) EnumDescriptor() ([]byte, []int) {
	return file_netconn_proto_rawDescGZIP(), []int{0, 1}
}

type Data_MsgType int32

const (
	Data_AUTHRESPONSE Data_MsgType = 0
	Data_UPDATESTATUS Data_MsgType = 1
	Data_DATA         Data_MsgType = 2
)

// Enum value maps for Data_MsgType.
var (
	Data_MsgType_name = map[int32]string{
		0: "AUTHRESPONSE",
		1: "UPDATESTATUS",
		2: "DATA",
	}
	Data_MsgType_value = map[string]int32{
		"AUTHRESPONSE": 0,
		"UPDATESTATUS": 1,
		"DATA":         2,
	}
)

func (x Data_MsgType) Enum() *Data_MsgType {
	p := new(Data_MsgType)
	*p = x
	return p
}

func (x Data_MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_netconn_proto_enumTypes[2].Descriptor()
}

func (Data_MsgType) Type() protoreflect.EnumType {
	return &file_netconn_proto_enumTypes[2]
}

func (x Data_MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_MsgType.Descriptor instead.
func (Data_MsgType) EnumDescriptor() ([]byte, []int) {
	return file_netconn_proto_rawDescGZIP(), []int{1, 0}
}

type Data_Status int32

const (
	Data_CONNECTWAIT    Data_Status = 0
	Data_CHIPSELECTWAIT Data_Status = 1
	Data_ACTING         Data_Status = 2
	Data_GAMEEND        Data_Status = 3
)

// Enum value maps for Data_Status.
var (
	Data_Status_name = map[int32]string{
		0: "CONNECTWAIT",
		1: "CHIPSELECTWAIT",
		2: "ACTING",
		3: "GAMEEND",
	}
	Data_Status_value = map[string]int32{
		"CONNECTWAIT":    0,
		"CHIPSELECTWAIT": 1,
		"ACTING":         2,
		"GAMEEND":        3,
	}
)

func (x Data_Status) Enum() *Data_Status {
	p := new(Data_Status)
	*p = x
	return p
}

func (x Data_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_netconn_proto_enumTypes[3].Descriptor()
}

func (Data_Status) Type() protoreflect.EnumType {
	return &file_netconn_proto_enumTypes[3]
}

func (x Data_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_Status.Descriptor instead.
func (Data_Status) EnumDescriptor() ([]byte, []int) {
	return file_netconn_proto_rawDescGZIP(), []int{1, 1}
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID string            `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	ClientID  string            `protobuf:"bytes,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Type      Action_ActionType `protobuf:"varint,3,opt,name=type,proto3,enum=netconn.Action_ActionType" json:"type,omitempty"`
	// Types that are assignable to Data:
	//	*Action_Req
	//	*Action_ObjectInfo
	//	*Action_DamageInfo
	//	*Action_Effect
	//	*Action_Signal
	//	*Action_Sound
	Data isAction_Data `protobuf_oneof:"data"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netconn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_netconn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_netconn_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *Action) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Action) GetType() Action_ActionType {
	if x != nil {
		return x.Type
	}
	return Action_AUTHENTICATE
}

func (m *Action) GetData() isAction_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Action) GetReq() *Action_AuthRequest {
	if x, ok := x.GetData().(*Action_Req); ok {
		return x.Req
	}
	return nil
}

func (x *Action) GetObjectInfo() []byte {
	if x, ok := x.GetData().(*Action_ObjectInfo); ok {
		return x.ObjectInfo
	}
	return nil
}

func (x *Action) GetDamageInfo() []byte {
	if x, ok := x.GetData().(*Action_DamageInfo); ok {
		return x.DamageInfo
	}
	return nil
}

func (x *Action) GetEffect() []byte {
	if x, ok := x.GetData().(*Action_Effect); ok {
		return x.Effect
	}
	return nil
}

func (x *Action) GetSignal() Action_SignalType {
	if x, ok := x.GetData().(*Action_Signal); ok {
		return x.Signal
	}
	return Action_CHIPSEND
}

func (x *Action) GetSound() []byte {
	if x, ok := x.GetData().(*Action_Sound); ok {
		return x.Sound
	}
	return nil
}

type isAction_Data interface {
	isAction_Data()
}

type Action_Req struct {
	Req *Action_AuthRequest `protobuf:"bytes,4,opt,name=req,proto3,oneof"`
}

type Action_ObjectInfo struct {
	ObjectInfo []byte `protobuf:"bytes,5,opt,name=objectInfo,proto3,oneof"`
}

type Action_DamageInfo struct {
	DamageInfo []byte `protobuf:"bytes,7,opt,name=damageInfo,proto3,oneof"`
}

type Action_Effect struct {
	Effect []byte `protobuf:"bytes,8,opt,name=effect,proto3,oneof"`
}

type Action_Signal struct {
	Signal Action_SignalType `protobuf:"varint,9,opt,name=signal,proto3,enum=netconn.Action_SignalType,oneof"`
}

type Action_Sound struct {
	Sound []byte `protobuf:"bytes,10,opt,name=sound,proto3,oneof"`
}

func (*Action_Req) isAction_Data() {}

func (*Action_ObjectInfo) isAction_Data() {}

func (*Action_DamageInfo) isAction_Data() {}

func (*Action_Effect) isAction_Data() {}

func (*Action_Signal) isAction_Data() {}

func (*Action_Sound) isAction_Data() {}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Data_MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=netconn.Data_MsgType" json:"type,omitempty"`
	// Types that are assignable to Data:
	//	*Data_AuthRes
	//	*Data_Status_
	//	*Data_RawData
	Data isData_Data `protobuf_oneof:"data"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netconn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_netconn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_netconn_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetType() Data_MsgType {
	if x != nil {
		return x.Type
	}
	return Data_AUTHRESPONSE
}

func (m *Data) GetData() isData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Data) GetAuthRes() *Data_AuthResponse {
	if x, ok := x.GetData().(*Data_AuthRes); ok {
		return x.AuthRes
	}
	return nil
}

func (x *Data) GetStatus() Data_Status {
	if x, ok := x.GetData().(*Data_Status_); ok {
		return x.Status
	}
	return Data_CONNECTWAIT
}

func (x *Data) GetRawData() []byte {
	if x, ok := x.GetData().(*Data_RawData); ok {
		return x.RawData
	}
	return nil
}

type isData_Data interface {
	isData_Data()
}

type Data_AuthRes struct {
	AuthRes *Data_AuthResponse `protobuf:"bytes,2,opt,name=authRes,proto3,oneof"`
}

type Data_Status_ struct {
	Status Data_Status `protobuf:"varint,3,opt,name=status,proto3,enum=netconn.Data_Status,oneof"`
}

type Data_RawData struct {
	RawData []byte `protobuf:"bytes,4,opt,name=rawData,proto3,oneof"`
}

func (*Data_AuthRes) isData_Data() {}

func (*Data_Status_) isData_Data() {}

func (*Data_RawData) isData_Data() {}

type Action_AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Action_AuthRequest) Reset() {
	*x = Action_AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netconn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_AuthRequest) ProtoMessage() {}

func (x *Action_AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netconn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_AuthRequest.ProtoReflect.Descriptor instead.
func (*Action_AuthRequest) Descriptor() ([]byte, []int) {
	return file_netconn_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Action_AuthRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action_AuthRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Action_AuthRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Data_AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg     string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	SessionID  string   `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	AllUserIDs []string `protobuf:"bytes,4,rep,name=allUserIDs,proto3" json:"allUserIDs,omitempty"`
}

func (x *Data_AuthResponse) Reset() {
	*x = Data_AuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netconn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_AuthResponse) ProtoMessage() {}

func (x *Data_AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netconn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_AuthResponse.ProtoReflect.Descriptor instead.
func (*Data_AuthResponse) Descriptor() ([]byte, []int) {
	return file_netconn_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Data_AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Data_AuthResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *Data_AuthResponse) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *Data_AuthResponse) GetAllUserIDs() []string {
	if x != nil {
		return x.AllUserIDs
	}
	return nil
}

var File_netconn_proto protoreflect.FileDescriptor

var file_netconn_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6e, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x6e, 0x22, 0xe0, 0x04, 0x0a, 0x06, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x2e, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6e, 0x65,
	0x74, 0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x65, 0x74,
	0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x20,
	0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x20, 0x0a, 0x0a, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x18, 0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x34, 0x0a, 0x06,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6e,
	0x65, 0x74, 0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x12, 0x16, 0x0a, 0x05, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x05, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x1a, 0x49, 0x0a, 0x0b, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x7e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43,
	0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x4f,
	0x42, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x4d, 0x4f, 0x56,
	0x45, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x44, 0x44,
	0x44, 0x41, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x44, 0x44, 0x45,
	0x46, 0x46, 0x45, 0x43, 0x54, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x4e, 0x44, 0x53,
	0x49, 0x47, 0x4e, 0x41, 0x4c, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x44, 0x44, 0x53, 0x4f,
	0x55, 0x4e, 0x44, 0x10, 0x07, 0x22, 0x3c, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x48, 0x49, 0x50, 0x53, 0x45, 0x4e, 0x44, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x4f, 0x43, 0x48, 0x49, 0x50, 0x53, 0x45, 0x4c, 0x45, 0x43,
	0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x44, 0x45, 0x41,
	0x44, 0x10, 0x02, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xbe, 0x03, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6e, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x36, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6e, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6e, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x07, 0x72, 0x61, 0x77, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x7e, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x73, 0x22, 0x37, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x41, 0x55, 0x54, 0x48, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x02, 0x22, 0x46, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43,
	0x54, 0x57, 0x41, 0x49, 0x54, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x48, 0x49, 0x50, 0x53,
	0x45, 0x4c, 0x45, 0x43, 0x54, 0x57, 0x41, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x43, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x41, 0x4d, 0x45, 0x45,
	0x4e, 0x44, 0x10, 0x03, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x3c, 0x0a, 0x07,
	0x4e, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x31, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0f, 0x2e, 0x6e, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0d, 0x2e, 0x6e, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x6e, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x2d, 0x6d, 0x69, 0x79, 0x6f,
	0x73, 0x68, 0x69, 0x2f, 0x67, 0x6f, 0x2d, 0x72, 0x6f, 0x63, 0x6b, 0x6d, 0x61, 0x6e, 0x65, 0x78,
	0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x65, 0x74, 0x2f, 0x6e, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_netconn_proto_rawDescOnce sync.Once
	file_netconn_proto_rawDescData = file_netconn_proto_rawDesc
)

func file_netconn_proto_rawDescGZIP() []byte {
	file_netconn_proto_rawDescOnce.Do(func() {
		file_netconn_proto_rawDescData = protoimpl.X.CompressGZIP(file_netconn_proto_rawDescData)
	})
	return file_netconn_proto_rawDescData
}

var file_netconn_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_netconn_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_netconn_proto_goTypes = []interface{}{
	(Action_ActionType)(0),     // 0: netconn.Action.ActionType
	(Action_SignalType)(0),     // 1: netconn.Action.SignalType
	(Data_MsgType)(0),          // 2: netconn.Data.MsgType
	(Data_Status)(0),           // 3: netconn.Data.Status
	(*Action)(nil),             // 4: netconn.Action
	(*Data)(nil),               // 5: netconn.Data
	(*Action_AuthRequest)(nil), // 6: netconn.Action.AuthRequest
	(*Data_AuthResponse)(nil),  // 7: netconn.Data.AuthResponse
}
var file_netconn_proto_depIdxs = []int32{
	0, // 0: netconn.Action.type:type_name -> netconn.Action.ActionType
	6, // 1: netconn.Action.req:type_name -> netconn.Action.AuthRequest
	1, // 2: netconn.Action.signal:type_name -> netconn.Action.SignalType
	2, // 3: netconn.Data.type:type_name -> netconn.Data.MsgType
	7, // 4: netconn.Data.authRes:type_name -> netconn.Data.AuthResponse
	3, // 5: netconn.Data.status:type_name -> netconn.Data.Status
	4, // 6: netconn.NetConn.TransData:input_type -> netconn.Action
	5, // 7: netconn.NetConn.TransData:output_type -> netconn.Data
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_netconn_proto_init() }
func file_netconn_proto_init() {
	if File_netconn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_netconn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netconn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netconn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netconn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_AuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_netconn_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Action_Req)(nil),
		(*Action_ObjectInfo)(nil),
		(*Action_DamageInfo)(nil),
		(*Action_Effect)(nil),
		(*Action_Signal)(nil),
		(*Action_Sound)(nil),
	}
	file_netconn_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Data_AuthRes)(nil),
		(*Data_Status_)(nil),
		(*Data_RawData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_netconn_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_netconn_proto_goTypes,
		DependencyIndexes: file_netconn_proto_depIdxs,
		EnumInfos:         file_netconn_proto_enumTypes,
		MessageInfos:      file_netconn_proto_msgTypes,
	}.Build()
	File_netconn_proto = out.File
	file_netconn_proto_rawDesc = nil
	file_netconn_proto_goTypes = nil
	file_netconn_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NetConnClient is the client API for NetConn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetConnClient interface {
	TransData(ctx context.Context, opts ...grpc.CallOption) (NetConn_TransDataClient, error)
}

type netConnClient struct {
	cc grpc.ClientConnInterface
}

func NewNetConnClient(cc grpc.ClientConnInterface) NetConnClient {
	return &netConnClient{cc}
}

func (c *netConnClient) TransData(ctx context.Context, opts ...grpc.CallOption) (NetConn_TransDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NetConn_serviceDesc.Streams[0], "/netconn.NetConn/TransData", opts...)
	if err != nil {
		return nil, err
	}
	x := &netConnTransDataClient{stream}
	return x, nil
}

type NetConn_TransDataClient interface {
	Send(*Action) error
	Recv() (*Data, error)
	grpc.ClientStream
}

type netConnTransDataClient struct {
	grpc.ClientStream
}

func (x *netConnTransDataClient) Send(m *Action) error {
	return x.ClientStream.SendMsg(m)
}

func (x *netConnTransDataClient) Recv() (*Data, error) {
	m := new(Data)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NetConnServer is the server API for NetConn service.
type NetConnServer interface {
	TransData(NetConn_TransDataServer) error
}

// UnimplementedNetConnServer can be embedded to have forward compatible implementations.
type UnimplementedNetConnServer struct {
}

func (*UnimplementedNetConnServer) TransData(NetConn_TransDataServer) error {
	return status.Errorf(codes.Unimplemented, "method TransData not implemented")
}

func RegisterNetConnServer(s *grpc.Server, srv NetConnServer) {
	s.RegisterService(&_NetConn_serviceDesc, srv)
}

func _NetConn_TransData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetConnServer).TransData(&netConnTransDataServer{stream})
}

type NetConn_TransDataServer interface {
	Send(*Data) error
	Recv() (*Action, error)
	grpc.ServerStream
}

type netConnTransDataServer struct {
	grpc.ServerStream
}

func (x *netConnTransDataServer) Send(m *Data) error {
	return x.ServerStream.SendMsg(m)
}

func (x *netConnTransDataServer) Recv() (*Action, error) {
	m := new(Action)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NetConn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "netconn.NetConn",
	HandlerType: (*NetConnServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransData",
			Handler:       _NetConn_TransData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "netconn.proto",
}
