api_addr: "0.0.0.0:8080"
data_stream_addr: "0.0.0.0:80"
db:
  type: "memory"
  conn_string: ""
log:
  debug_log: true
  file: "router.log"
debug:
  enabled: true
  client1_id: "tester1"
  client1_key: "testtest"
  client2_id: "tester2"
  client2_key: "testtest"
