api_addr: "0.0.0.0:3000"
log:
  file: "server.log"
client_data:
  - client_id: "tester1"
    client_key: "testtest"
    user_id: "804f3fc5-328f-49c6-969d-ac559d95108a"
    session_id: "session1"
  - client_id: "tester2"
    client_key: "testtest"
    user_id: "473e4e85-1f34-4cd3-a8b1-5b34c863c276"
    session_id: "session1"
session_data:
  - id: "session1"
    owner_client_id: "tester1"
    guest_client_id: "tester2"
