name: Docker Image build and Push

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'data/**'
      - 'test/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build server image
      run: docker build -t smiyoshi/rockmanexe .
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      run: |
        docker push smiyoshi/rockmanexe
