name: Test

on:
  - push

jobs:
  unit-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  router-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requires
        run: sudo apt-get install -y jq
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run server
        run: |
          cd cmd/fakeserver
          go build
          ./fakeserver &
          cd ../../cmd/router
          go build
          ./router &
      - name: API Test
        working-directory: ./test/router
        run: ./api_test.sh
      - name: Client Test
        working-directory: ./test/router/client_test
        run: go run main.go
      - name: Connection Test
        working-directory: ./test/router/conn_test
        run: go run main.go
